<div>
    <form method="post" action="<?php echo $videoForm->getAction(); ?>" enctype="multipart/form-data">
        <?php if (!isset($isEdit)) { ?>
        <div>
            <?php echo $videoForm->render('video'); ?>
        </div>
        <?php } ?>
        <div>
            <?php echo $videoForm->label('title'); ?>
            <?php echo $videoForm->render('title'); ?>
        </div>
        <div>
            <?php echo $videoForm->render('description'); ?>
        </div>
        <div>
            <?php foreach ($tagForm->getElements() as $tag) {
                echo $tag->label($tag->getName());
                echo $tag->render($tag->getName());
            } ?>
        </div>
        <div>
            <?php echo $videoForm->render('submit'); ?>
        </div>
    </form>
</div>
