<div>
    <form method="post" action="<?php echo $form->getAction(); ?>" enctype="multipart/form-data">
        <div>
            <?php echo $form->label('username'); ?>
            <?php echo $form->render('username'); ?>
        </div>
        <div>
            <?php echo $form->label('password'); ?>
            <?php echo $form->render('password'); ?>
        </div>
        <div>
            <?php echo $form->render('submit'); ?>
        </div>
    </form>
</div>
